get:
  tags:
    - Task
  summary: 'Create a task form.'
  operationId: create_task
  responses:
    200:
      description: 'The create task information (JSON) or (HTML).'
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: ../../models/task.yml
              meta:
                type: object
        text/html:
          schema:
            type: string
            example: '<html><body><form method="POST" action="/resource/lead/tasks">Create a task</form></body></html>'
    401:
      description: Unauthorized
    403:
      description: Forbidden
