parameters:
  -
    in: path
    name: id
    required: true
    description: 'The task id.'
    schema:
      type: string
      format: uuid
get:
  tags:
    - Task
  summary: 'Get a task by id.'
  operationId: get_task
  responses:
    200:
      description: 'The task data.'
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: ../../models/task.yml
              meta:
                type: object
    401:
      description: Unauthorized
    403:
      description: Forbidden
delete:
  tags:
    - Task
  summary: 'Delete a task by id.'
  operationId: delete_task
  responses:
    204:
      description: 'The task has been deleted.'
    401:
      description: Unauthorized
    403:
      description: Forbidden
    423:
      description: 'The task is locked. Unlock to delete.'
patch:
  tags:
    - Task
  summary: 'Patch a task by id.'
  operationId: patch_task
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../../requests/task/patch.yml
  responses:
    200:
      description: 'The task has been patched.'
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: ../../models/task.yml
              meta:
                type: object
    401:
      description: Unauthorized
    403:
      description: Forbidden
    422:
      description: 'Validation error'
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  title:
                    type: array
                    items:
                      type: string
                      example: 'The title field is required.'
    423:
      description: 'The task is locked. Unlock to patch.'
