get:
  tags:
    - Task
  summary: 'Get tasks from the index.'
  operationId: get_tasks_index
  responses:
    200:
      description: 'Get the tasks from the index.'
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../../models/task.yml
              meta:
                type: object
    401:
      description: Unauthorized
    403:
      description: Forbidden
post:
  tags:
    - Task
  summary: 'Create a task.'
  operationId: post_task
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../../requests/task/post.yml
  responses:
    200:
      description: 'The created task.'
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: ../../models/task.yml
              meta:
                type: object
    401:
      description: Unauthorized
    403:
      description: Forbidden
    422:
      description: 'Validation error'
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  title:
                    type: array
                    items:
                      type: string
                      example: 'The title field is required.'
    423:
      description: 'The task is locked. Unlock to patch.'
