openapi: 3.0.3
servers:
  -
    url: 'https://resource.example.com'
    description: 'Production server'
  -
    url: 'https://resource.staging.example.com'
    description: 'Staging server'
  -
    url: 'https://resource.dev.example.com'
    description: 'Dev server'
info:
  title: Playground Lead Resource
  description: ''
  termsOfService: ''
  # contact:
  #   email: support@example.com
  version: 73.0.0
externalDocs:
  description: ''
  url: ''
tags:
  -
    name: Campaign
    description: 'Manage campaigns in storage.'
  -
    name: Goal
    description: 'Manage goals in storage.'
  -
    name: Lead
    description: 'Manage leads in storage.'
  -
    name: Opportunity
    description: 'Manage opportunities in storage.'
  -
    name: Plan
    description: 'Manage plans in storage.'
  -
    name: Region
    description: 'Manage regions in storage.'
  -
    name: Report
    description: 'Manage reports in storage.'
  -
    name: Source
    description: 'Manage sources in storage.'
  -
    name: Task
    description: 'Manage tasks in storage.'
  -
    name: Team
    description: 'Manage teams in storage.'
  -
    name: Teammate
    description: 'Manage teammates in storage.'
paths:
  '/resource/lead/campaigns/{id}':
    $ref: paths/campaigns/id.yml
  /resource/lead/campaigns:
    $ref: paths/campaigns/index.yml
  '/resource/lead/campaigns/lock/{id}':
    $ref: paths/campaigns/lock.yml
  '/resource/lead/campaigns/restore/{id}':
    $ref: paths/campaigns/restore.yml
  '/resource/lead/goals/{id}':
    $ref: paths/goals/id.yml
  /resource/lead/goals:
    $ref: paths/goals/index.yml
  '/resource/lead/goals/lock/{id}':
    $ref: paths/goals/lock.yml
  '/resource/lead/goals/restore/{id}':
    $ref: paths/goals/restore.yml
  '/resource/lead/leads/{id}':
    $ref: paths/leads/id.yml
  /resource/lead/leads:
    $ref: paths/leads/index.yml
  '/resource/lead/leads/lock/{id}':
    $ref: paths/leads/lock.yml
  '/resource/lead/leads/restore/{id}':
    $ref: paths/leads/restore.yml
  '/resource/lead/opportunities/{id}':
    $ref: paths/opportunities/id.yml
  /resource/lead/opportunities:
    $ref: paths/opportunities/index.yml
  '/resource/lead/opportunities/lock/{id}':
    $ref: paths/opportunities/lock.yml
  '/resource/lead/opportunities/restore/{id}':
    $ref: paths/opportunities/restore.yml
  '/resource/lead/plans/{id}':
    $ref: paths/plans/id.yml
  /resource/lead/plans:
    $ref: paths/plans/index.yml
  '/resource/lead/plans/lock/{id}':
    $ref: paths/plans/lock.yml
  '/resource/lead/plans/restore/{id}':
    $ref: paths/plans/restore.yml
  '/resource/lead/regions/{id}':
    $ref: paths/regions/id.yml
  /resource/lead/regions:
    $ref: paths/regions/index.yml
  '/resource/lead/regions/lock/{id}':
    $ref: paths/regions/lock.yml
  '/resource/lead/regions/restore/{id}':
    $ref: paths/regions/restore.yml
  '/resource/lead/reports/{id}':
    $ref: paths/reports/id.yml
  /resource/lead/reports:
    $ref: paths/reports/index.yml
  '/resource/lead/reports/lock/{id}':
    $ref: paths/reports/lock.yml
  '/resource/lead/reports/restore/{id}':
    $ref: paths/reports/restore.yml
  '/resource/lead/sources/{id}':
    $ref: paths/sources/id.yml
  /resource/lead/sources:
    $ref: paths/sources/index.yml
  '/resource/lead/sources/lock/{id}':
    $ref: paths/sources/lock.yml
  '/resource/lead/sources/restore/{id}':
    $ref: paths/sources/restore.yml
  '/resource/lead/tasks/{id}':
    $ref: paths/tasks/id.yml
  /resource/lead/tasks:
    $ref: paths/tasks/index.yml
  '/resource/lead/tasks/lock/{id}':
    $ref: paths/tasks/lock.yml
  '/resource/lead/tasks/restore/{id}':
    $ref: paths/tasks/restore.yml
  '/resource/lead/teams/{id}':
    $ref: paths/teams/id.yml
  /resource/lead/teams:
    $ref: paths/teams/index.yml
  '/resource/lead/teams/lock/{id}':
    $ref: paths/teams/lock.yml
  '/resource/lead/teams/restore/{id}':
    $ref: paths/teams/restore.yml
  '/resource/lead/teammates/{id}':
    $ref: paths/teammates/id.yml
  /resource/lead/teammates:
    $ref: paths/teammates/index.yml
  '/resource/lead/teammates/lock/{id}':
    $ref: paths/teammates/lock.yml
  '/resource/lead/teammates/restore/{id}':
    $ref: paths/teammates/restore.yml
components:
  schemas:
    Campaign:
      $ref: models/campaign.yml
    Goal:
      $ref: models/goal.yml
    Lead:
      $ref: models/lead.yml
    Opportunity:
      $ref: models/opportunity.yml
    Plan:
      $ref: models/plan.yml
    Region:
      $ref: models/region.yml
    Report:
      $ref: models/report.yml
    Source:
      $ref: models/source.yml
    Task:
      $ref: models/task.yml
    Team:
      $ref: models/team.yml
    Teammate:
      $ref: models/teammate.yml
